<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Dartalla')->setSeparator(' - ')->setAutoEscape(false) ?>
        <!--        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">-->
        <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('icons/fontawesome/css/all.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
        $this->headScript()
        ?>
    </head>
    <body>
        <?= $this->partial('header'); ?>
        <div id="wrapper">
            <?= $this->partial('sidebar'); ?>
            <div id="content">
                <?=
                        $this->navigation('navigation')
                        ->breadcrumbs()
                        ->setMinDepth(0)
                        ->setSeparator(' ▶' . PHP_EOL)
                        ->setPartial('breadcrumbs');
                ?>
                <?= $this->content ?>
            </div>
        </div>
        <?=
                $this->inlineScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.4.1.min.js'))
        ?>
    </body>
</html>
