<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <?php foreach ($this->pages as $key => $page): ?>
            <li class="breadcrumb-item">
                <?php if ($key < count($this->pages) - 1): ?>
                    <a href="<?= $page->getHref(); ?>" aria-current="page"><?= $page->getLabel(); ?></a>
                <?php else: ?>
                    <?= $page->getLabel(); ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ol>
</nav>
