<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation">
    <a class="navbar-brand" href="<?= $this->url('dtl-admin') ?>">
        <img src="<?= $this->basePath('img/dartalla-brand.png') ?>" height="30" alt=""/>&nbsp;Dartalla
    </a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle Navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
            </li>
        </ul>
        <?php if ($this->identity()): ?>
            <div class="navbar-nav dropdown">
                    
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenu">
                    <a href="#" class="dropdown-item">
                        <i class="fa fa-user"></i> Editar Perfil
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="<?= $this->url('logout'); ?>" class="dropdown-item">
                        <i class="fas fa-sign-out-alt" aria-hidden="true"></i> Sair
                    </a>
                </div>
            </div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="" class="btn btn-outline-secondary ml-1">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        <?php endif; ?>
    </div>
</nav>
