<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light" role="navigation">
    <a class="navbar-brand mb-0 h1" href="<?= $this->url('dtl-admin'); ?>">Dartalla</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#dtlNavbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="dtlNavbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">

            </li>
        </ul>
        <?php if ($this->identity()): ?>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dtlNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?= $this->identity()->getFullName(); ?>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dtlNavbarDropdown">
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-user"></i> Editar Perfil
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="<?= $this->url('logout'); ?>" class="dropdown-item">
                            <i class="fas fa-sign-out-alt"></i> Sair
                        </a>
                    </div>
                </li>
            </ul>
        <?php endif; ?>
    </div>
</nav>
