<?php foreach ($this->container as $key => $page): ?>
    <?php if (!$page->hasPages()): ?>
        <li class="nav-item">
            <a href="<?= $this->url($page->route); ?>" class="nav-link <?= $page->class; ?>" >
                <?= $page->icon; ?>  
                <?= $page->label; ?>
            </a>
        </li>
    <?php else: ?>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dtlNavbarDropdown<?= $key; ?>" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <?= $page->label; ?>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dtlNavbarDropdown<?= $key; ?>">
                <?php foreach ($page->pages as $subpage): ?>
                    <a href="<?=$subpage->getHref();?>" class="dropdown-item">
                        <?=$subpage->getLabel();?>
                    </a>
                <?php endforeach; ?>
            </div>
        </li>
    <?php endif; ?>
<?php endforeach; ?>
